import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../../src/styles/home.module.css";
import Image from "next/image";
import heroImg from "../../public/assets/hero.png";
import { GetServerSideProps, GetStaticProps } from "next";
import { collection, getCountFromServer, getDocs } from "firebase/firestore";
import { db } from "../services/firebaseConnection";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  posts: number;
  comments: number;
}

export default function Home({ posts, comments }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas+ | Organize suas tarefas com eficiência</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image
            className={styles.hero}
            alt="Logo Tarefas+"
            src={heroImg}
            priority={true}
          />
        </div>
        <h1 className={styles.title}>
          Sistema feito para você organizar <br />
          seus estudos e tarefas
        </h1>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+{posts} posts</span>
          </section>
          <section className={styles.box}>
            <span>+{comments} comentarios</span>
          </section>
        </div>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const commentRef = collection(db, "comments");

  const postRef = collection(db, "tarefas");

  const commentSnapshot = await getCountFromServer(commentRef);
  const postSnapshot = await getCountFromServer(postRef);

  return {
    props: {
      posts: postSnapshot.data().count,
      comments: commentSnapshot.data().count,
    },
    revalidate: 60,
  };
};
